[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
either = "1.8"
regex = "1.10"
strum = "0.24"
strum_macros = "0.24"
clust = "0.9.0"
tokio = { version = "1.42.0", features = ["full"] }
tokio-macros = "2.4.0"
once_cell = "1.19"